stages:
  - test

cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
    - bin/

test:
  stage: test
  only:
    - kubeadm
    - kubeadm-test
  script:
    - go test ./cmd/kubeadm/app/cmd
    - go test ./pkg/util/json
    - go test ./pkg/util/yaml
  tags:
    - Minik8s