stages:
  - build
  - test

cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
    - bin/

build:
  stage: build
  only:
    - master
    - develop
  script:
    # Set proxy for go
    - go env -w GO111MODULE=on
    - go env -w GOPROXY=https://goproxy.cn,direct
    # Setup development environment
    - go mod tidy
    # Build by Makefile 
    - make build
    # Run all components in Minik8s
    - ./bin/apiserver
    - ./bin/scheduler
    - ./bin/kube-controller-manager
    - ./bin/kubelet
    - ./bin/knative       
    - ./bin/kubectl join --config ./testcases/gitlab-runner.yaml  # Join itself

test:
  stage: test
  only:
    - master
    - develop
  script:
    # Test all testcases in minik8s dir
    - go test ./...
  tags:
    - Minik8s