kind: Deployment
metadata:
  name: deployment_test
spec: 
  replicas: 2
  selector: test
  template: 
    kind: Pod
    metadata:
      name: test
      labels:
        app: test-pod
        node: vmeet1
    spec:
      volumes:
      - name: shared-data
        hostPath: /root/test_vo
    
      containers:
    
      - name: go1
        image: docker.io/library/golang:latest
        volumeMounts:
          - name: shared-data
            mountPath: /mnt
        ports:
          - containerPort: 8080
        command: 
          - bash
    
      - name: go2
        image: docker.io/library/golang:latest
        volumeMounts:
          - name: shared-data
            mountPath: /go/src
        ports:
          - containerPort: 80
        command: 
          - bash